"""
Django settings for habittracker project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import importlib.util
from pathlib import Path
import os
import sys
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# get environment variables from .env
load_dotenv(BASE_DIR / '.env')

SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-ug4!da0...')


def module_is_available(module_name):
    try:
        return importlib.util.find_spec(module_name) is not None
    except ModuleNotFoundError:
        return False


ALLAUTH_AVAILABLE = module_is_available('allauth')
SOCIAL_PROVIDER_MODULES = {
    'google': 'allauth.socialaccount.providers.google',
    'microsoft': 'allauth.socialaccount.providers.microsoft',
    'github': 'allauth.socialaccount.providers.github',
    'facebook': 'allauth.socialaccount.providers.facebook',
}
AVAILABLE_SOCIAL_PROVIDERS = [
    provider_id
    for provider_id, module_name in SOCIAL_PROVIDER_MODULES.items()
    if ALLAUTH_AVAILABLE and module_is_available(module_name)
]
SOCIAL_LOGIN_ENABLED = ALLAUTH_AVAILABLE and bool(AVAILABLE_SOCIAL_PROVIDERS)


def env_bool(name, default=False):
    return os.getenv(name, str(default)).strip().lower() in {'1', 'true', 'yes', 'on'}


def social_app_from_env(prefix, *, extra_settings=None):
    client_id = os.getenv(f'{prefix}_CLIENT_ID', '').strip()
    secret = os.getenv(f'{prefix}_SECRET', '').strip()
    if not client_id or not secret:
        return []

    app_config = {
        'client_id': client_id,
        'secret': secret,
        'key': '',
    }
    if extra_settings:
        app_config['settings'] = extra_settings
    return [app_config]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', True)
# Keep local runserver usable even when the environment is configured like production.
if not DEBUG and 'runserver' in sys.argv:
    DEBUG = True

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')
BITCOIN_WALLET_ADDRESS = os.getenv('BITCOIN_WALLET', 'bc1q2hljnlh2lycamk6t9nl3f7rtyd639lf5ec6jlj')
APP_NAME = os.getenv('APP_NAME', 'Habit Tracker').strip() or 'Habit Tracker'
SANDBOX_GMAIL_ADDRESS = os.getenv('SANDBOX_GMAIL_ADDRESS', 'habittracker001@gmail.com').strip() or 'habittracker001@gmail.com'
CONTACT_RECIPIENT_EMAIL = SANDBOX_GMAIL_ADDRESS
SANDBOX_GMAIL_APP_PASSWORD = os.getenv('SANDBOX_GMAIL_APP_PASSWORD', '').strip()
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', SANDBOX_GMAIL_ADDRESS).strip() or SANDBOX_GMAIL_ADDRESS
EMAIL_HOST = os.getenv('EMAIL_HOST', '').strip()
if not EMAIL_HOST and EMAIL_HOST_USER.endswith('@gmail.com'):
    EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '').strip()
if not EMAIL_HOST_PASSWORD and EMAIL_HOST_USER == SANDBOX_GMAIL_ADDRESS and SANDBOX_GMAIL_APP_PASSWORD:
    EMAIL_HOST_PASSWORD = SANDBOX_GMAIL_APP_PASSWORD
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', False)
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '20'))
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', '').strip()
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', '').strip()
MPESA_ENVIRONMENT = os.getenv('MPESA_ENVIRONMENT', 'sandbox')
MPESA_CONSUMER_KEY = os.getenv('MPESA_CONSUMER_KEY', '')
MPESA_CONSUMER_SECRET = os.getenv('MPESA_CONSUMER_SECRET', '')
MPESA_SHORTCODE = os.getenv('MPESA_SHORTCODE', '')
MPESA_PASSKEY = os.getenv('MPESA_PASSKEY', '')
APP_BASE_URL = os.getenv('APP_BASE_URL', '').rstrip('/')
MPESA_CALLBACK_URL = os.getenv('MPESA_CALLBACK_URL', '').strip()
if not MPESA_CALLBACK_URL and APP_BASE_URL:
    MPESA_CALLBACK_URL = f'{APP_BASE_URL}/mpesa/callback/'
MPESA_TRANSACTION_TYPE = os.getenv('MPESA_TRANSACTION_TYPE', 'CustomerPayBillOnline')
MPESA_PARTYB = os.getenv('MPESA_PARTYB', '')

if not EMAIL_BACKEND:
    if EMAIL_HOST and EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
        EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    else:
        EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

if not DEFAULT_FROM_EMAIL:
    if EMAIL_HOST_USER:
        DEFAULT_FROM_EMAIL = f'{APP_NAME} <{EMAIL_HOST_USER}>'
    else:
        DEFAULT_FROM_EMAIL = 'no-reply@habittracker.local'

SERVER_EMAIL = os.getenv('SERVER_EMAIL', DEFAULT_FROM_EMAIL)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'tracker',
]

if ALLAUTH_AVAILABLE:
    INSTALLED_APPS += [
        'django.contrib.sites',
        'allauth',
        'allauth.account',
        'allauth.socialaccount',
        *[SOCIAL_PROVIDER_MODULES[provider_id] for provider_id in AVAILABLE_SOCIAL_PROVIDERS],
    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if ALLAUTH_AVAILABLE:
    MIDDLEWARE.insert(-1, 'allauth.account.middleware.AccountMiddleware')

ROOT_URLCONF = 'habittracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tracker.context_processors.app_shell',
            ],
        },
    },
]

WSGI_APPLICATION = 'habittracker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# For Vercel/production, use DATABASE_URL environment variable
# For local development, use SQLite

import dj_database_url

DATABASE_URL = os.getenv('DATABASE_URL', '')

if DATABASE_URL:
    # Production database (PostgreSQL, MySQL, etc.)
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Development database (SQLite)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv('TIME_ZONE', 'Africa/Nairobi')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CRISPY_TEMPLATE_PACK = 'bootstrap5'

SITE_ID = int(os.getenv('SITE_ID', '1'))
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'
AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend']
SOCIALACCOUNT_PROVIDERS = {}
SOCIALACCOUNT_LOGIN_ON_GET = False
SOCIALACCOUNT_STORE_TOKENS = False
SOCIALACCOUNT_QUERY_EMAIL = True

if ALLAUTH_AVAILABLE:
    AUTHENTICATION_BACKENDS.append('allauth.account.auth_backends.AuthenticationBackend')
    SOCIALACCOUNT_ADAPTER = 'tracker.adapters.TrackerSocialAccountAdapter'
    SOCIALACCOUNT_AUTO_SIGNUP = True
    SOCIALACCOUNT_PROVIDERS = {
        'google': {
            'APPS': social_app_from_env('GOOGLE_OAUTH'),
            'SCOPE': ['profile', 'email'],
            'AUTH_PARAMS': {
                'access_type': 'online',
            },
            'OAUTH_PKCE_ENABLED': True,
            'FETCH_USERINFO': True,
        },
        'github': {
            'APPS': social_app_from_env('GITHUB_OAUTH'),
            'SCOPE': ['read:user', 'user:email'],
        },
        'microsoft': {
            'APPS': social_app_from_env(
                'MICROSOFT_OAUTH',
                extra_settings={
                    'tenant': os.getenv('MICROSOFT_OAUTH_TENANT', 'common').strip() or 'common',
                },
            ),
        },
        'facebook': {
            'APPS': social_app_from_env('FACEBOOK_OAUTH'),
            'METHOD': 'oauth2',
            'SCOPE': ['email', 'public_profile'],
            'FIELDS': ['id', 'email', 'first_name', 'last_name', 'name', 'picture'],
            'AUTH_PARAMS': {
                'auth_type': 'reauthenticate',
            },
        },
    }
