# Generated by Django 6.0.3 on 2026-03-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='lightning_invoice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa (Daraja)'), ('bitcoin', 'Bitcoin'), ('bitcoin_lightning', 'Bitcoin Lightning')], max_length=20),
        ),
    ]
