# Generated by Django 6.0.3 on 2026-03-23 20:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_donation_lightning_invoice_alter_donation_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_payload',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='status_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='area',
            field=models.CharField(blank=True, default='General', max_length=64),
        ),
        migrations.AddField(
            model_name='habit',
            name='color',
            field=models.CharField(default='#ff7a59', max_length=7),
        ),
        migrations.AddField(
            model_name='habit',
            name='end_condition',
            field=models.CharField(blank=True, default='Never', max_length=64),
        ),
        migrations.AddField(
            model_name='habit',
            name='every_n_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='habit',
            name='reminders',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='habit',
            name='repeat',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='habit',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='habit',
            name='time_of_day',
            field=models.CharField(blank=True, default='Morning,Afternoon,Evening', max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='primary_color',
            field=models.CharField(default='#ff7a59', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='secondary_color',
            field=models.CharField(default='#3256ff', max_length=7),
        ),
        migrations.AlterField(
            model_name='habit',
            name='unit',
            field=models.CharField(choices=[('hours', 'Hours'), ('km', 'Kilometers'), ('reps', 'Repetitions'), ('money', 'Money'), ('times', 'Times'), ('boolean', 'Yes/No')], default='times', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='font',
            field=models.CharField(choices=[('default', 'Manrope'), ('montserrat', 'Montserrat'), ('space_grotesk', 'Space Grotesk'), ('playfair', 'Playfair Display'), ('merriweather', 'Merriweather'), ('courier', 'Courier New')], default='default', max_length=32),
        ),
    ]
