# Generated by Django 6.0.3 on 2026-03-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='consistency_plan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habit',
            name='habit_stack_cue',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habit',
            name='identity_statement',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habit',
            name='tiny_step',
            field=models.TextField(blank=True, default=''),
        ),
    ]
