# Generated by Django 6.0.3 on 2026-03-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_habit_consistency_plan_habit_habit_stack_cue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='oauth_profile_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='oauth_profile_source',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='oauth_profile_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
